fix: 🐛 Ensure undefined is not serialzed
Prior to this change, messages that 'undefined' are attempted to
be serialized - this would cause the following exception to be
raised:

```bash
TypeError: Cannot read properties of undefined (reading 'type')
```

After this change, a simple non-null assertion is made to ensure
the type of the value is not accessed if the value is undefined